# encoding: utf-8
source 'https://supermarket.chef.io'

cookbook 'os-hardening', git: 'https://github.com/dev-sec/chef-os-hardening.git'
cookbook 'ssh-hardening', git: 'https://github.com/dev-sec/chef-ssh-hardening.git'
cookbook 'audit', path: '../../'
