---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  #chef_version: 13.12.14
  chef_version: 14

transport:
  name: dokken

provisioner:
  name: dokken
  chef_log_level: info
  chef_output_format: minimal

verifier:
  name: inspec
  sudo: false

platforms:
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: centos-6
  driver:
    image: dokken/centos-6
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-6
  driver:
    image: oraclelinux:6
- name: oracle-7
  driver:
    image: oraclelinux:7
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install -y procps
- name: debian-8
  driver:
    image: debian:8
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd

suites:
  - name: default # run inspec locally
    run_list:
      - recipe[test_helper::setup]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          - name: ssh-baseline
            supermarket: dev-sec/ssh-baseline
  - name: inspec-attributes
    run_list:
      - recipe[test_helper::setup]
      - recipe[test_helper::create_file]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - git: https://github.com/mhedgpeth/attribute-file-exists-profile.git
        attributes:
          file: /opt/kitchen/cache/attribute-file-exists.test
  - name: chef-node-enabled
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - url: https://github.com/adamleff/inspec-profile-chef-node-attributes/archive/master.tar.gz
        chef_node_attribute_enabled: true
  - name: chef-node-disabled
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - url: https://github.com/adamleff/inspec-profile-chef-node-attributes/archive/master.tar.gz
  - name: missing-profile-no-fail
    run_list:
      - recipe[test_helper::setup]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/this-is-not-available.zip
    includes:
      - ubuntu-18.04
  - name: missing-profile-fail
    run_list:
      - recipe[test_helper::setup]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        fail_if_not_present: true
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/this-is-not-available.zip
    includes:
      - ubuntu-18.04
  - name: compliance # compliance direct reporting
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        server: <%= ENV['COMPLIANCE_API'] %>
        token: <%= ENV['COMPLIANCE_ACCESSTOKEN'] %>
        owner: admin
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          - git: https://github.com/dev-sec/tests-ssh-hardening.git
          - name: ssh-baseline
            supermarket: dev-sec/ssh-baseline
  - name: chef15-compatible-inspec
    run_list:
      - recipe[test_helper::force_inspec_core]
      - recipe[audit::default]
    driver:
      chef_version: 15
    provisioner:
      chef_options: ' -z --chef-license accept-no-persist'
    attributes:
      audit:
        reporter: json-file
        inspec_version: 3.0.9
        fail_if_not_present: true
  - name: gem-install-core-version4
    run_list:
      - recipe[test_helper::install_inspec]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        inspec_version: 4.3.2
        fail_if_not_present: true
  - name: gem-install-core-version3
    run_list:
      - recipe[test_helper::install_inspec]
      - recipe[audit::default]
    driver:
      chef_version: 14
    attributes:
      audit:
        reporter: json-file
        inspec_version: 3.0.9
        fail_if_not_present: true
  - name: gem-install-core-version2
    run_list:
      - recipe[test_helper::install_inspec]
      - recipe[audit::default]
    driver:
      chef_version: 14
    attributes:
      audit:
        reporter: json-file
        inspec_version: 2.1.67
        fail_if_not_present: true
  - name: hash
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          ssh-hardening:
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          ssh-baseline:
            supermarket: dev-sec/ssh-baseline
