---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: bento/centos-7.1
  - name: bento/centos-6.8
  - name: bento/centos-5.11

suites:
  - name: default
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        collector: json-file
        profiles:
          - name: dev-sec/linux-baseline
