---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: false

platforms:
- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
- name: ubuntu-15.10
  driver:
    image: ubuntu:15.10
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: centos-6.6
  driver:
    image: centos:6.6
- name: centos-6.7
  driver:
    image: centos:6.7
    intermediate_instructions:
      - RUN yum install -y initscripts
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-6.6
  driver:
    image: oraclelinux:6.6
- name: oracle-6.7
  driver:
    image: oraclelinux:6.7
- name: oracle-7.1
  driver:
    image: oraclelinux:7.1
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install -y procps
- name: debian-8
  driver:
    image: debian:8
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd

suites:
  - name: default # run inspec locally
    run_list:
      - recipe[git::default]
      - recipe[audit::default]
    attributes:
      audit:
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          - git: https://github.com/dev-sec/tests-ssh-hardening.git
          - name: ssh
            supermarket: hardening/ssh-hardening
  - name: compliance # compliance direct reporting
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        server: <%= ENV['COMPLIANCE_API'] %>
        token: <%= ENV['COMPLIANCE_ACCESSTOKEN'] %>
        owner: admin
        profiles: *profiles

  - name: inspec_package # compliance direct reporting
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        inspec_package_source: 'https://packages.chef.io/stable/el/6/inspec-1.4.1-1.el6.x86_64.rpm'
        inspec_package_libpath: '/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib'
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/tests-ssh-hardening
