---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: '192.168.33.202'}]


provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[compliance::default]
    attributes:
